# Generated by Django 6.0.7 on 2026-08-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
